### ISSUE TITLE
Zmiana wielkości liter na trzy możliwe transformacje(upper, lower, capitalize)

### ISSUE THREAD

**Issue by Yorlock** [Yorlock/Text-Transformer#3]
Pracochłonność: 1h

- Funkcja do upper
- Funkcja do lower
- Funkcja do capitalize

**Comment by Anukia** [comment]
Funkcjonalności nie wydzielone do osobnych funkcji, zaimplementowane w złym pliku

**Comment by Anukia** [comment]
Poprawiono implementację na wzorzec dekoratora oraz przeniesiono funckjonalności do odpowiedniego pliku.

DO POPRAWKI:
http://localhost:8080/kot na klawiaturze?transforms=capitalize zamieni na kot Na Klawiaturze
ALE http://localhost:8080/ kot na klawiaturze?transforms=capitalize zamieni już dobrze na Kot Na Klawiaturze
czemu?? 
podobnie jest z IntToWord (patrz Issues dotyczący tego)
