### ISSUE TITLE
Zmiana liczb całkowitych na tekst w języku polskim

### ISSUE THREAD

**Issue by Yorlock** [Yorlock/Text-Transformer#5]
Pracochłonność: 2h

**Comment by Anukia** [comment]
Zrobiona zamiana liczb całkowitych do 1k oraz ułamków do dziesiętnych.
DO POPRAWKI:
odmiana w części dziesiętnej i setnej przy 1 i 2 (0.2 -> i DWIE a nie DWA jak jest, podobne z 0.1 -> jedna zamiast jeden)
